### ISSUE TITLE
Update duckdb version to 1.1.0 

### ISSUE THREAD

**Issue by mtravis** [Krizz/fetch_overture#1]
@Krizz great work on this app. I've been having a go and I'm impressed how well it works with the cutting of boundaries, etc 
Really lightweight script too. 

Version 1.1.0 of DuckDB has added [support for geoparquet](https://duckdb.org/2024/09/09/announcing-duckdb-110#spatial-features) so if you update to that you can strip out the need for `ST_GeomFromWKB(geometry) AS geometry`

I can set up a PR tomorrow if you like.

**Comment by Krizz** [comment]
Thank you for the positive feedback @mtravis! 

That's nice. I've wasted lot of time by constantly forgetting to convert the geometry column. Unfortunately the duckdb npm package is still @1.0.0.
